version: '3.1'

services:
#  server:
#    container_name: psy-app
#    build:
#      context: .
#    ports:
#      - "9090:9090"
#    depends_on:
#      psydb:
#        condition: service_healthy
#    environment:
#      - POSTGRES_URL=jdbc:postgresql://psydb:5432/psynote
  psydb:
    container_name: psy-db
    image: postgres:14
    restart: always
    hostname: psydb
    ports:
      - "5002:5432"
    environment:
      POSTGRES_USER : psyuser
      POSTGRES_PASSWORD: 77664488
      POSTGRES_DB: psynote
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
