version: '3.1'

services:
  server:
    container_name: psy-app-dev
    build:
      context: .
    ports:
      - "9002:9002"
    depends_on:
      psydb:
        condition: service_healthy
    environment:
      BOT_NAME: psy_note_book_test_bot
      BOT_TOKEN: 6904427337:AAEq3B8uvrNwB6GZ-cyu4nvL9lpEpAcoA-Q
      SPRING_DATASOURCE_URL: jdbc:postgresql://psydb:5002/psynote
      SPRING_DATASOURCE_USERNAME: psyuser
      SPRING_DATASOURCE_PASSWORD: 77664488

  psydb:
    container_name: psy-db-dev
    image: postgres:14
    restart: always
    hostname: psydb
    ports:
      - "5002:5432"
    environment:
      POSTGRES_USER: psyuser
      POSTGRES_PASSWORD: 77664488
      POSTGRES_DB: psynote
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
