version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
