server:
  port: 9010
spring:
  application:
    name: psychologist-notebook-bot
  datasource:
    username: psyuser
    password: 77664488
    url: jdbc:postgresql://psydb:5002/psynote
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
bot:
  name: psy_local_bot
  token: 7361935702:AAGoMNQrc0AcDJT6C28a__xOgqlC1SgybrM

logging:
  level:
    ru.boris.psychologist.notebook: DEBUG
